### ISSUE TITLE
[Suggestion/Api/WuTest] Win10 labs page with excluded '(..)' ones 

### ISSUE THREAD

**Issue by nickurt** [hounsell/BuildFeed#15]
The list for 'win10 labs' will be growing very fast these days
> https://buildfeed.net/api/getwin10labs/

Since we loading all these labs into [TeamGnome/WUTest](https://github.com/TeamGnome/WUTest), the scanning will take minutes more, up to ~ 20min.

Is it possible to exclude all the labs that contains '([..])' ?

e.g.

> fbl_cortana_dev01(brentcou)
> fbl_kpg_kernel(dedesa)

Since these labs will be never pushed out in WU/WS architecture ..

**Comment by hounsell** [comment]
k, done.
https://buildfeed.net/api/getwin10labs/
