### ISSUE TITLE
[Proposal] Renaming LevelOfFlight to (new) API 'standards' ...

### ISSUE THREAD

**Issue by nickurt** [hounsell/BuildFeed#23]
In the new API is Microsoft using WIS/WIF/OSG/MSIT/Canary and not more Low/Medium/High, is it a good idea to change the FlightNames (FlightHigh/FlightLow) to the new 'standards' (FlightsWIF/FlightsWIS)?

**Comment by hounsell** [comment]
Agreed.

What I'll probably do is as we move to MongoDB, I'll make the levels editable in the admin panel, have them independent objects in the database.
