### ISSUE TITLE
Branch page for private/xpsp_mce gives 404 ...

### ISSUE THREAD

**Issue by nickurt** [hounsell/BuildFeed#26]
The branch page for private/xpsp_mce gives 404 due a forward slash in the name ...

https://buildfeed.net/lab/private/xpsp_mce

**Comment by hounsell** [comment]
God I hate Microsoft. What dipshit thought it was a good idea to put a slash in a lab name. I hope they burn in hell for all eternity.

**Comment by hounsell** [comment]
fixed, no thanks to Microsoft.
