### ISSUE TITLE
301 Redirect for old RSS flight levels

### ISSUE THREAD

**Issue by hounsell** [hounsell/BuildFeed#33]
/rss/feed/high/ => /rss/feed/osg/ ?
/rss/feed/medium/ => /rss/feed/msit/ ?
/rss/feed/low/ => /rss/feed/wif/ ?

**Comment by nickurt** [comment]
LGTM, do this.

**Comment by AirportsFan** [comment]
They make more sense now since older ring levels are not considered anymore. Go for it.
