### ISSUE TITLE
Hijri calendar is used when viewed in Arabic language

### ISSUE THREAD

**Issue by AirportsFan** [hounsell/BuildFeed#54]
When using Arabic interface to view builds information, the date is in Hijri formatting (Possibly set to Saudi Arabia since they use it by default).
e.g. 14390 buildstring in Arabic is 10.0.14390.0.rs1_release.371007-1452. This also includes all pages showing date.

**Comment by AirportsFan** [comment]
The buildstrings are now fine. All good.

**Comment by hounsell** [comment]
Perhaps we should move Arabic from the default "ar" locale, which mimics ar-SA, to ar-AE, which is seems to be a good tradeoff between generic arabic and westernised dates and times.
