### ISSUE TITLE
forgotten password，how do I reset the password

### ISSUE THREAD

**Issue by hstmodo** [hounsell/BuildFeed#63]
I've forgotten my password, so I want to reset password, but I don't know how to reset the password,I can‘t find reset password page.

**Comment by hounsell** [comment]
There is no reset password page at the moment, but then there's no real user system to access at the moment. The only people who need access at the moment are the contributors. Any other user won't even have their account approved, and so won't be able to login even if they do know their password.

This will change in the future, I've got big plans for that part of the site, but it's not going to matter until then.
