### ISSUE TITLE
Improve language builds

### ISSUE THREAD

**Issue by 810** [hounsell/BuildFeed#66]
There need to check if there just 1 build.

Should be:
1 Build or 2 Builds

Now:
1 Builds or 2 Builds

**Comment by hounsell** [comment]
The only problem is it's not a consistent thing across languages.

In most western european languages, you're right in suggesting it's simply a matter of singular of plural. But in Russian, I believe as an example, the suffix can be one of a number of different choices depending on the exact quantity. Other languages have similar things. You'll end up building a whole system and requiring god knows how many translation phrases just to get an accurate pluralisation.


So I'm lazy and just leave it as one option. I guess you could always do like {0} Build(s).
