### ISSUE TITLE
Allow bulk-import

### ISSUE THREAD

**Issue by hounsell** [hounsell/BuildFeed#73]
It'd probably be handy if we could bulk-import build strings by just pasting in a long list of build strings and assuming some sensible defaults.

Maybe have a drop down to select the source type for all of them.

**Comment by AirportsFan** [comment]
Is it possible the user can enter some sort of key-row before the list in pasting box? for example {major}.{minor}.{arch}.{branch}.{timestamp}, followed by build strings in next lines in which the site would learn the correct sequence to be used.
