### ISSUE TITLE
How to compile BuildFeed.

### ISSUE THREAD

**Issue by danielchim** [hounsell/BuildFeed#83]
I downloaded this project for learning,but how can i compile it?

**Comment by hounsell** [comment]
Hope the README that I've actually written helps you get started. If there's something I'm missing, which I probably am, just drop another comment in here and I'll be happy to help you out.

**Comment by danielchim** [comment]
Also how can i turn back to .net framework 4.6? Because i am running windows 7,and i cannot mount the buildfeed folder.

**Comment by hounsell** [comment]
You'll want to update TargetFrameworkVersion in the csproj files, and then replace all the 4.7 references in the Web.config
