### ISSUE TITLE
Website font-face 

### ISSUE THREAD

**Issue by kulaLin** [hounsell/BuildFeed#88]
hello, 
Could you change font-face on your website ?

beacuse website font-face showing Chinese character so ugly from the "Fira Sans"

why not use "Source Han Sans"

"Source Han Sans" much better than "Fira Sans" pretty

or fallback system fonts
e.g. 
Segoe UI 
Microsoft JhengHei
Meiryo
Microsoft YaHei

Thanks.

**Comment by hounsell** [comment]
I've added explicit font stacks for CJK locales:
https://github.com/hounsell/BuildFeed/blob/master/BuildFeed/res/css/default.scss#L12-L30

Just followed the standard Windows fonts.

I'm open to better suggestions. Web Fonts aren't really an option with CJK locales unfortunately. They're heavy and CDN options are basically non-existent.

**Comment by kulaLin** [comment]
Sorry for late reply.

I updated some, please check and it
[https://github.com/hounsell/BuildFeed/pull/90](url)

**Comment by nickurt** [comment]
Thanks @kulaLin, I merge'd your pull request
