### ISSUE TITLE
Please update my data to Credits page

### ISSUE THREAD

**Issue by kulaLin** [hounsell/BuildFeed#89]
Link Chu -> GT Wang

remove my twitter and github 

add my website [http://mkvq.blogspot.com/](url)

Thanks

**Comment by nickurt** [comment]
@kulaLin, can you make a pull-request with the change(s) you want?, I will review and merge it after that.

**Comment by kulaLin** [comment]
How to view Credits page on github?

**Comment by nickurt** [comment]
@kulaLin you can change this page, [credits.cshtml](https://github.com/hounsell/BuildFeed/blob/master/BuildFeed/Views/support/credits.cshtml)
